image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - docker build -t pjsua2-docker-image .
  - docker run
      -e SIP_ID_URI=${SIP_ID_URI}
      -e SIP_REGISTRAR_URI=${SIP_REGISTRAR_URI}
      -e SIP_USERNAME=${SIP_USERNAME}
      -e SIP_PASSOWRD=${SIP_PASSOWRD}
      --mount type=bind,source="$(pwd)",target=/app
      pjsua2-docker-image
      /app/build.sh
